### PR TITLE
Fix dashboard wording

### LINKED ISSUE #15: Dashboard:  typos, inconsistent use of lower and upper case, etc.
1. 4 instances of Rotki should be changed to rotki.
2. Is: Be it on a blockchain, a <br>DeFi protocol or on one of the supported exchanges.
Should be: Be it on a blockchain, <br>a DeFi protocol or on one of the supported exchanges.
3. Profit/Loss Report. 6 instances. Should be Profit/loss report or other consistent transcription across the website.
4. Ethereum Protocols. Should be Ethereum protocols
5. Premium Features. Should be Premium features
6. Graphs and Statistics. Should be Graphs and statistics
7. Space missing: Networth over time. Should be: Net worth over time
8. Typo: Asset amount and total asset value over times. Should be: Asset amount and total asset value over time
9. Is: Defi Historical accounting, profit and loss. Should be: DeFi historical accounting, profit and loss
10. Is: See the entire list of activities you have done when interacting with a Defi protocol. Should be: See the entire list of activities you have done when interacting with a DeFi protocol.
11. Is: Decentralized Exchanges. Should be: Decentralized exchanges
12. Is: Advanced Staking Should be: Advanced staking

### PR DESCRIPTION
**Pull request by lukicenturi**
Fix #15 

- [x] Add i18n support (currently for home page)

- Fix Typos
- [x] 4 instances of Rotki should be changed to rotki.
- [x] Is: Be it on a blockchain, a
DeFi protocol or on one of the supported exchanges.
Should be: Be it on a blockchain,
a DeFi protocol or on one of the supported exchanges.
- [x] Profit/Loss Report. 6 instances. Should be Profit/loss report or other consistent transcription across the website.
- [x] Ethereum Protocols. Should be Ethereum protocols
- [x] Premium Features. Should be Premium features
- [x] Graphs and Statistics. Should be Graphs and statistics
- [x] Space missing: Networth over time. Should be: Net worth over time
- [x] Typo: Asset amount and total asset value over times. Should be: Asset amount and total asset value over time
- [x] Is: Defi Historical accounting, profit and loss. Should be: DeFi historical accounting, profit and loss
- [x] Is: See the entire list of activities you have done when interacting with a Defi protocol. Should be: See the entire list of activities you have done when interacting with a DeFi protocol.
- [x] Is: Decentralized Exchanges. Should be: Decentralized exchanges
- [x] Is: Advanced Staking Should be: Advanced staking

### CODE REVIEW

File: components/features/details/Dashboard.vue [hunk 1]
```diff
@@ -9,14 +9,16 @@
       />
     </template>
     <feature-details>
-      <template #subtitle> Assets and Liabilities </template>
-      View all of your assets and liabilities and your exposure to each as a
-      percentage of your net worth.
+      <template #subtitle>
+        {{ $t('home.dashboard.details.asset_and_liabilities.title') }}</template
+      >
```
Comment (kelsos) [inline components/features/details/Dashboard.vue:14]: nitpick: maybe we can add a space before the closing to avoid the template tag breaking

File: components/features/details/Dashboard.vue [hunk 2]
```diff
@@ -9,14 +9,16 @@
...
+      {{ $t('home.dashboard.details.asset_and_liabilities.description') }}
     </feature-details>
     <feature-details>
-      <template #subtitle> Net worth over time</template>
-      Users can also see a graph of how their total net worth is evolving over
-      time. Free users are limited to the last 2 weeks.
+      <template #subtitle>
+        {{ $t('home.dashboard.details.net_worth_over_time.title') }}</template
+      >
```
Comment (kelsos) [inline components/features/details/Dashboard.vue:20]: same here

File: components/Hero.vue [hunk 3]
```diff
@@ -29,17 +29,20 @@
...
-        rotki is a local-first application with a strong focus on user privacy.
+        <template #title>{{ $t('home.advantages.local_app.title') }} </template>
+        <div>{{ $t('home.advantages.local_app.description') }}</div>
       </info>
       <info>
-        <template #title> Own your data </template>
-        Your financial data is kept encrypted in your system and not shared with
-        third parties.
+        <template #title
+          >{{ $t('home.advantages.own_your_data.title') }}
```
Comment (kelsos) [inline components/Hero.vue:43]: also here make sure that the tag closing doesn't break

File: components/features/details/DefiDetails.vue [hunk 4]
```diff
@@ -1,39 +1,48 @@
...
+        >
+        {{ $t('home.eth_protocols.protocols.uniswap.description') }}
       </DefiProtocol>
       <DefiProtocol :image="require('~/assets/img/defi/balancer.png')">
-        <template #name>Balancer</template>
-        Your current LP balances, and trades
+        <template #name>
+          {{ $t('home.eth_protocols.protocols.balancer.title') }}</template
+        >
+        {{ $t('home.eth_protocols.protocols.balancer.description') }}
```
Comment (kelsos) [inline components/features/details/DefiDetails.vue:42]: again make sure the tag doesn't break

File: components/premium/details/GraphsStatistics.vue [hunk 5]
```diff
@@ -1,15 +1,14 @@
...
-      <div>Networth over time</div>
-      <div>Asset amount and total asset value over times</div>
-      <div>Breakdown of total net worth per location</div>
-      <div>Breakdown of total net worth per asset</div>
-    </div>
+    <template #title>
+      {{
+        $t('home.premium_features.features.graphs_and_statistics.title')
+      }}</template
+    >
```
Comment (kelsos) [inline components/premium/details/GraphsStatistics.vue:7]: same here

File: components/premium/details/PremiumDefi.vue [hunk 6]
```diff
@@ -1,10 +1,13 @@
...
-    various protocol to be informed via email when certain conditions are met.
-  </premium-feature>
+    <template #title>
+      {{ $t('home.premium_features.features.premium_defi.title') }}
+    </template>
+
+    {{
+      $t('home.premium_features.features.premium_defi.detail')
+    }}</premium-feature
+  >
```
Comment (kelsos) [inline components/premium/details/PremiumDefi.vue:10]: also here

File: components/premium/details/Transactions.vue [hunk 7]
```diff
@@ -1,11 +1,13 @@
...
+      {{ $t('home.premium_features.features.unlimited_histories.title') }}
     </template>
-    Free users have a limit on the number of transactions, deposits, withdrawals
-    and other events they can see and process. Premium users have no such limit.
-  </premium-feature>
+
+    {{
+      $t('home.premium_features.features.unlimited_histories.detail')
+    }}</premium-feature
+  >
```
Comment (kelsos) [inline components/premium/details/Transactions.vue:10]: as above

Comment (kelsos) [inline components/premium/details/Transactions.vue:10]: same

File: package.json [hunk 8]
```diff
@@ -24,6 +24,7 @@
   "dependencies": {
     "@metamask/detect-provider": "1.2.0",
     "@nuxtjs/axios": "5.13.1",
+    "@nuxtjs/i18n": "^7.2.0",
```
Comment (kelsos) [inline package.json:27]: make sure to pin the exact version here

File: locales/en.json [hunk 9]
```diff
@@ -0,0 +1,135 @@
...
+          "title": "DeFi historical accounting, profit and loss",
+          "detail": " See the entire list of activities you have done when interacting with a DeFi protocol. Get the profit/loss report for each protocol. Set watchers for various protocol to be informed via email when certain conditions are met."
+        },
+        "dex_support": {
+          "title": "Decentralized exchanges",
+          "detail": "See how much you have in each liquidity pool. All your Uniswap and Balancer LP join/exit events are shown along with the total profit/loss per pool.{0}{0}Uniswap and Balancer trades are taken into account in the tax report for premium users."
+        },
+        "premium_staking": {
+          "title": "Advanced staking",
+          "detail": "See how much of the token is staked per account.{0}What is the expected APR.{0}How much of the token you have earned by staking across all accounts.{0}{0}See a list of all your staking events with links to the corresponding transactions."
```
[the remark this answers is not in the document]
Comment (lukicenturi) [reply locales/en.json:109]: there is, I can put `\n` in the localization text. But I need to add `white-space-preline` to the element, do you prefer this way better?

[the remark this answers is not in the document]
Comment (kelsos) [reply locales/en.json:109]: No for the time being let's keep it like this

[the remark this answers is not in the document]
Comment (lukicenturi) [reply locales/en.json]: Okay, the rest is updated

[the remark this answers is not in the document]
Comment (lukicenturi) [reply locales/en.json:109]: Okay, the rest is updated

**Review by kelsos — APPROVED** [review]
lgtm
